/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapRouteImport } from './routes/map'
import { Route as MausamRouteImport } from './routes/mausam'
import { Route as PashudhanRouteImport } from './routes/pashudhan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MausamRoute = MausamRouteImport.update({
  id: '/mausam',
  path: '/mausam',
  getParentRoute: () => rootRouteImport,
} as any)
const PashudhanRoute = PashudhanRouteImport.update({
  id: '/pashudhan',
  path: '/pashudhan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/mausam': typeof MausamRoute
  '/pashudhan': typeof PashudhanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/mausam': typeof MausamRoute
  '/pashudhan': typeof PashudhanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/mausam': typeof MausamRoute
  '/pashudhan': typeof PashudhanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/map' | '/mausam' | '/pashudhan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/map' | '/mausam' | '/pashudhan'
  id: '__root__' | '/' | '/map' | '/mausam' | '/pashudhan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  MausamRoute: typeof MausamRoute
  PashudhanRoute: typeof PashudhanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mausam': {
      id: '/mausam'
      path: '/mausam'
      fullPath: '/mausam'
      preLoaderRoute: typeof MausamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pashudhan': {
      id: '/pashudhan'
      path: '/pashudhan'
      fullPath: '/pashudhan'
      preLoaderRoute: typeof PashudhanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  MausamRoute: MausamRoute,
  PashudhanRoute: PashudhanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
